name: coupons_backend
description: An asta_coupons backend
version: 0.1.0
authors: 
  - Daniel Negi <dnegi@asta.uni-paderborn.de>
  - Leon Tappe <ltappe@mail.upb.de>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  aqueduct: ^4.0.0-b1 
  uuid: ^2.2.2
  mime: 0.9.6+3
  http_server: ^0.9.8+1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1 

dependency_overrides:
  postgres: 2.1.1
